include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_relative_lib_imports: true
    avoid_print: false
    require_trailing_commas: true
    prefer_single_quotes: true
    always_declare_return_types: true
